name: Run Tests

on:
  push:
    branches:
      - "**"
    tags:
      - "**"

jobs:
  # tests:
  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       node-version:
  #         - 18
  #         - 20

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Set up NodeJS ${{ matrix.node-version }}
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: ${{ matrix.node-version }}

  #     - name: Install dependencies
  #       run: npm ci

  #     - name: Run tests
  #       run: npm run test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: "Install rollup (temporary fix for: https://github.com/npm/cli/issues/4828)"
        run: npm i -O @rollup/rollup-linux-x64-gnu
      - name: Run build of each package
        run: npm run build
